export type HurdatFileRow = {
  storm_id: string,
  storm_name: string,
  meas_ymd: string,
  meas_hm: string,
  rec_identifier: string,
  storm_status: string,
  lat_rel: string,
  lng_rel: string,
  msw_kt: number,
  mcb_mb: number,
  ne_34: number,
  se_34: number,
  sw_34: number,
  nw_34: number,
  ne_50: number,
  se_50: number,
  sw_50: number,
  nw_50: number,
  ne_64: number,
  se_64: number,
  sw_64: number,
  nw_64: number,
}